[package]
name = "crates_and_cargo"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Just trying things out, don't look!"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
